---

- name: Add Nginx repo
  yum_repository:
    name: nginx
    description: nginx stable repo
    baseurl: http://nginx.org/packages/centos/$releasever/$basearch/
    gpgcheck: yes
    gpgkey: https://nginx.org/keys/nginx_signing.key

- name: Install latest version of Nginx
  yum:
    name: nginx
    state: latest

- name: Ensure Nginx is started and enabled
  service:
    name: nginx
    state: started
    enabled: true

- name: Copy the Nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    validate: "/usr/sbin/nginx -t -c %s"
  notify:
    - restart nginx

- name: Add vhosts
  template:
    src: vhost.conf.j2
    dest: /etc/nginx/conf.d/{{ item }}.conf
  with_items: "{{nginx_vhosts}}"
  notify:
    - reload nginx
