---

nginx_user: nginx
nginx_worker_processes: "{{ansible_processor_count}}"
nginx_worker_connections: 1024

nginx_http_params:
  sendfile: "on"
  tcp_nopush: "on"
  keepalive_timeout: "65"
  access_log: "/var/log/nginx/access.log main"
  error_log: "/var/log/nginx/error.log warn"
